version: "3.9"

networks:
  mysql-phpmyadmin:
    name: mysql-phpmyadmin
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: serveur_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Greta92
      MYSQL_DATABASE: marketlev
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    ports:
      - "3307:3306"
    networks:
      - mysql-phpmyadmin
    restart: always # Added for better resilience

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: serveur_phpmyadmin
    volumes:
      - ./projet:/var/www/html/projet
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306 # Corrected port to default MySQL port
    ports:
      - "8888:80"
    networks:
      - mysql-phpmyadmin
    restart: always # Added for better resilience
